parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  semi: "off"
  "@typescript-eslint/semi": "error"
  "@typescript-eslint/member-ordering": "error"
  quotes: "off"
  "@typescript-eslint/quotes":
    - "error"
    - "single"
  indent: "off"
  "@typescript-eslint/indent":
    - "error"
    - 2
